[package]
name = "shape_provider"
version = "0.1.0"
edition = "2024"

[dependencies]
shapes = { path = "../shapes" }
# tokio + native-tls
sqlx = { version = "0.8", features = [ "runtime-tokio", "tls-native-tls", "postgres" ] }