[package]
name = "shapes_api"
version = "0.1.0"
edition = "2024"

[dependencies]
shapes = { path = "../shapes" }
shape_repositories = {path = "../shape_repositories"}
sqlx = { version = "0.8", features = [ "runtime-tokio", "tls-native-tls", "postgres" ] }
axum = { version = "0.8", features = ["macros"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"]  }
serde_json = "1.0.150"
axum-test = { version = "20.1.0" }
tower = { version = "0.5.3" }
tower-http = { version = "0.7.0", features = ["trace"]}

[dev-dependencies]
mockall = "0.14.0"