version: '3.8'

services:
  db:
    image: postgres:17.6-trixie
    restart: always
    environment:
      POSTGRES_DB: shapesdb
      POSTGRES_USER: [USER_NAME]
      POSTGRES_PASSWORD: [PASSWORD]
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:9.8.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: [EMAIL]
      PGADMIN_DEFAULT_PASSWORD: [PASSWORD]
    ports:
      - "8080:80"
    depends_on:
      - db
